// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddKey'](arg1, arg2, arg3, arg4);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DecryptKey(arg1) {
  return window['go']['main']['App']['DecryptKey'](arg1);
}

export function DeleteKey(arg1) {
  return window['go']['main']['App']['DeleteKey'](arg1);
}

export function DeleteTag(arg1, arg2) {
  return window['go']['main']['App']['DeleteTag'](arg1, arg2);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetTagUsageCount(arg1) {
  return window['go']['main']['App']['GetTagUsageCount'](arg1);
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function ImportData(arg1) {
  return window['go']['main']['App']['ImportData'](arg1);
}

export function ImportWithResolution(arg1, arg2) {
  return window['go']['main']['App']['ImportWithResolution'](arg1, arg2);
}

export function LoadKeys() {
  return window['go']['main']['App']['LoadKeys']();
}

export function OpenImportFileDialog() {
  return window['go']['main']['App']['OpenImportFileDialog']();
}

export function SearchKeys(arg1, arg2) {
  return window['go']['main']['App']['SearchKeys'](arg1, arg2);
}

export function UpdateKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateKey'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3);
}
