// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKey(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<any>;

export function CreateTag(arg1:string,arg2:string):Promise<any>;

export function DecryptKey(arg1:string):Promise<string>;

export function DeleteKey(arg1:string):Promise<boolean>;

export function DeleteTag(arg1:string,arg2:boolean):Promise<boolean>;

export function ExportData():Promise<string>;

export function GetAllTags():Promise<Array<any>>;

export function GetTagUsageCount(arg1:string):Promise<number>;

export function GetTags():Promise<Array<any>>;

export function ImportData(arg1:string):Promise<any>;

export function ImportWithResolution(arg1:string,arg2:Record<string, string>):Promise<any>;

export function LoadKeys():Promise<Array<any>>;

export function OpenImportFileDialog():Promise<string>;

export function SearchKeys(arg1:string,arg2:string):Promise<Array<any>>;

export function UpdateKey(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<any>;

export function UpdateTag(arg1:string,arg2:string,arg3:string):Promise<any>;
